### ISSUE TITLE
Submit darklaf issues

### ISSUE THREAD

**Issue by weisJ** [Furrrlo/MARS#1]
Hi I have seen that you are using darklaf and experienced some issues. I would really appreciate if you could submit corresponding issues to the [darklaf issue tracker](https://github.com/weisJ/darklaf/issues), so I can fix them upstream for everyone :)

**Comment by Furrrlo** [comment]
It looks like it's already fixed in latest.integration (with this commit [here](https://github.com/weisJ/darklaf/commit/774e4fea4db6a13e40cfcc99142fc64ff67ee8b7#diff-c1d2dc7689ce347dcdff0929bda23e239ec42cc223511637db9d90ba9d5ff8ef) which adds the `StringUtil#orEmpty(String)` calls to WindowsTitlePane). Should I open an issue regardless?

**Comment by weisJ** [comment]
Thats grat to hear! In this case you don't need to submit an issue. How about the problem with the accent colour not being respected using the `ThemeSettings` class. Is this fixed for you with the latest integration version?

**Comment by Furrrlo** [comment]
Oh yeah, I had forgotten about that. Opened an issue

**Comment by weisJ** [comment]
Thank you :)
